### ISSUE TITLE
Restore from snapshot

### ISSUE THREAD

**Issue by jmcarp** [awslabs/aws-servicebroker-rds#1]
Does this broker allow for restoring from snapshots of other instances that the user has access to? If so, I didn't see how from the source or documentation, and it would be helpful to document. If not, would this be possible to add?

**Comment by rniksch** [comment]
The current service plan does not cater for the restore from snapshot. 
I will update the Docs to reflect this.

I will add this to a list of features which we are  aiming to release through the year.
Thank you for the feedback.

**Comment by jaymccon** [comment]
we are archiving this repo, this will be tracked in our new repo here: https://github.com/awslabs/aws-servicebroker/issues/2
