### ISSUE TITLE
Create unique credentials on each binding

### ISSUE THREAD

**Issue by jmcarp** [awslabs/aws-servicebroker-rds#2]
Similar to #1, I'm wondering if this feature exists or could be supported in the future.

It looks like this broker provides the master database credentials on bind. For security and compliance reasons, we need to create a new credential pair on each bind (and destroy it on unbind). That could be implemented using http://docs.ansible.com/ansible/latest/postgresql_user_module.html and similar modules to create a user on bind, then pass the resulting credentials to the user.

**Comment by jaymccon** [comment]
@jmcarp I've flagged this to be discussed further, there are some challenges around how bind has been implemented in the service broker that prevent this from being easily attainable at the moment. 

If possible, can you provide any additional details on use-case for the multiple bind/unbind and your compliance requirements.

**Comment by jaymccon** [comment]
we are archiving this repository and will close this issue and track it in https://github.com/awslabs/aws-servicebroker/issues/1
